### PR TITLE
Update package versions to fix security vulnerabilities

### PR DESCRIPTION
**Pull request by jags14385**
- Update the dependencies to ensure npm audit doesn't throw security error / warning messages
- Updated gulpfile.js for gulp v4.

### CODE REVIEW

**Comment by jags14385** [comment]
@akarpz @dbradf  Please let me know if this works

**Comment by akarpz** [comment]
Could you update the changelog? Also I see the package-lock is not currently committed, I'm not sure if that's something we want to do. @dbradf any comment

**Review by akarpz — APPROVED** [review]

**Comment by jags14385** [comment]
Updated the Changelog.
According to the docs here : https://docs.npmjs.com/files/package-lock.json  , package-lock.json is intended to be present in the source repo.

Please let me know how you want to proceed

**Comment by jags14385** [comment]
@akarpz  Can you please merge & publish the changes too. I do not have write access

**Review by akarpz — APPROVED** [review]

**Pull request merged**
